name: tools
dependencies:
  - scipy
  - scikit-learn
  - netCDF4
  - matplotlib
  - cython
  - pandas
  - tabulate
  - cffi
  - openpyxl
  - h5py
  - pip
  - pip:
     - acoustics
     - SoundFile
     - brewer2mpl
     - imbalanced-learn
